version: '2'

services:
  apinodejs:
    hostname: apinodejs
    #image: owncloudci/nodejs
    build: .
    container_name: apinodejs
    working_dir: /app
    volumes:
      - './:/app'
    ports:
      - "7002:3000"
    depends_on:
      - apimongo
    links:
      - apimongo
    environment:
      - NODE_ENV=development
    stdin_open: true

  apimongo:
    hostname: apimongo
    image: mongo:latest
    container_name: apimongo
    ports:
      - "7003:27017"